include $(GNUSTEP_MAKEFILES)/common.make

# The application to be compiled
LIBRARY_NAME = Id3

# C sources files to be compiled
Id3_C_FILES = md5.c

# The Objective-C source files to be compiled
Id3_OBJC_FILES = \
id3V1Tag.m \
id3V2Frame.m\
id3V2Tag.m\
MP3Header.m\
TagAPI.m\
V20FrameSet.m\
V23FrameSet.m\
V24FrameSet.m


include $(GNUSTEP_MAKEFILES)/library.make



